### ISSUE TITLE
请问那个调试参数的界面在哪里？

### ISSUE THREAD

**Issue by zwxbest** [wudixiaop/ShaderlabVS#10]
VS2015，SDK在可选功能中的，增加之后，找不到设置external program的地方。

**Comment by wudixiaop** [comment]
在 ShaderlabVS 那个项目的属性窗口那里

**Comment by zwxbest** [comment]
是您的项目？

**Comment by wudixiaop** [comment]
我指的是在 VS 里面打开方案之后，里面有个叫 ShaderlabVS 的 project。 它的属性窗口就是设置 external program 的地方

**Comment by zwxbest** [comment]
一直就没有那个ShaderlabVS 项目。安装插件和sdk了。

**Comment by wudixiaop** [comment]
看看是否和下图的一样？

<img width="722" alt="2016-10-31 14 45 00" src="https://cloud.githubusercontent.com/assets/5707242/19846265/a9587920-9f78-11e6-9360-1e56eb94e777.png">

**Comment by zwxbest** [comment]
这是您这个项目的代码吧。不是所有VS项目都可以吧。

**Comment by wudixiaop** [comment]
external program 是 Visual Studio 提供的功能, 只要 VS 支持的项目都可以。

**Comment by zwxbest** [comment]
我找不到。。。
![capture](https://cloud.githubusercontent.com/assets/9984560/19847031/c888bf20-9f7e-11e6-9431-c8fc7e65e148.PNG)

**Comment by wudixiaop** [comment]
你难道是想用来调试 shader  文件？ Readme 里面写的是开发 ShaderlabVS  这个插件需要设置 external program... 现在 shader 的调试是不支持的。

**Comment by zwxbest** [comment]
呃，那好吧，谢谢了。
