### ISSUE TITLE
配色问题

### ISSUE THREAD

**Issue by lifangjie** [wudixiaop/ShaderlabVS#11]
vss2015深色主题配色有点奇怪, 是本身就设置成这样的吗.

**Comment by wudixiaop** [comment]
目前没有适配主题，需要自己定义颜色

按下面步骤：

1. 打开 VS -> 工具 -> 选项 -> 环境 -> 字体和颜色,
2. 显示其设置 下拉列表中选择 文本编辑器 （如果没改过，这就是默认的）。
3. 在 显示项(D) 文字下面的列表框中选择以 “Shaderlab-” 开头的项，然后改变前景色

改完后确定就可以了

参照： #1

**Comment by lifangjie** [comment]
阔以阔以,  非常感谢
