### ISSUE TITLE
大括号不能自动补全和缩进？

### ISSUE THREAD

**Issue by xrjervis** [wudixiaop/ShaderlabVS#12]
![snip_20170302235704](https://cloud.githubusercontent.com/assets/13498557/23515019/f78172a6-ffa3-11e6-872e-619759fe9491.png)

**Comment by wudixiaop** [comment]
现在没有想过功能呢。最近打算做些插件的更新，看看能不能加进去

**Comment by wudixiaop** [comment]
已添加大括号自动补全，本地验证过缩进没有问题。

**Comment by wudixiaop** [comment]
下载包过几天补上

**Comment by xrjervis** [comment]
![snip_20170311230838](https://cloud.githubusercontent.com/assets/13498557/23824337/b5e567ae-06af-11e7-9e75-86106531def3.png)
您好，安装0.8版本后发现大括号是可以不全，但是仍然无法自动缩进，输入回车后光标会移动到下一行开头，而非和上一行代码对齐的位置

**Comment by wudixiaop** [comment]
打开VS->工具 ->选项->文本编辑器->ShaderlabVS->制表->缩进 里面选择的是 “块” 吗？

<img width="743" alt="2017-03-11 23 26 48" src="https://cloud.githubusercontent.com/assets/5707242/23824462/4ad9c1d2-06b2-11e7-91a2-200c5f1e74f4.png">

**Comment by xrjervis** [comment]
之前没有在这里设置，现在好了，非常感谢！ 也建议将此项配置在README中进行说明~
