### ISSUE TITLE
Support VS 2017

### ISSUE THREAD

**Issue by wudixiaop** [wudixiaop/ShaderlabVS#13]

**Comment by EduardDraude** [comment]
Could you please upload a release for VS2017? Thanks!

**Comment by wudixiaop** [comment]
Here is a package which didn't test .. May I ask you try it?

[ShaderlabVS-2017.vsix.zip](https://github.com/wudixiaop/ShaderlabVS/files/1084009/ShaderlabVS-2017.vsix.zip)

**Comment by AntEduard** [comment]
Thanks for the fast reply! I installed the extension, but somehow it does not apply correctly. It is listed in the VS extension overview and in option. In Options in the General tab the Statement completion section is not enabled and greyed out, so I can't enable it. Did I miss something?

**Comment by SugoiDev** [comment]
I compiled it myself to test and can confirm: statement completion items are all greyed out for me too.

**Comment by wudixiaop** [comment]
@AntEduard @SugoiDev It's by design. Statement Completion greyed out will not affact the completion feature of ShaderlabVS.

**Comment by AntEduard** [comment]
okay, then it is not working for me :/

**Comment by AntEduard** [comment]
okay, then it is not working for me :/
sorry

**Comment by wudixiaop** [comment]
Interesting. I installed the package attached in my previous comment and test it in my side:
![test](https://user-images.githubusercontent.com/5707242/27288904-c0dd6ace-553a-11e7-8a24-cf7b90459401.jpg)

@AntEduard What's the version of VS2017 in your side?

**Comment by SugoiDev** [comment]
It works on my side as well with the version I compiled locally and community VS.

**Comment by AntEduard** [comment]
Hey! I think I found the problem.
When installing the extension you can show the installation protocoll. There are the supported version listed. So my version Community Version 15.2 is not supported. Just 14.0.
I would compile it myself, but here I have no permissions to do so.

**Comment by whuop** [comment]
This seems to be working for me, except it broke my indentation on newline. When pressing return it goes to the start of the next line, using no indentation at all. I used the package uploaded by wudixiaop in this issue.

**Comment by wudixiaop** [comment]
@AntEduard it should have 14.0 to 16.0 support. I'm not sure why it's not support on your side. 

@whuop  what's the value of Options->Text Editor->ShaderlabVS->Tabs-> Indenting? Is it 'block'? If not, set it to 'block' and try again.
