### ISSUE TITLE
Publish the extension to the Visual Studio Gallery

### ISSUE THREAD

**Issue by TobiasWehrum** [wudixiaop/ShaderlabVS#14]
Publishing the extension to the Visual Studio Gallery allows easy installing right in Visual Studio and automatic updates.

https://www.visualstudio.com/da-dk/docs/integrate/ide/extensions/publish_extensions/publish

**Comment by wudixiaop** [comment]
https://marketplace.visualstudio.com/items?itemName=ShaderlabVS2019.ShaderlabVS
