### ISSUE TITLE
Have a optional - Ctrl + K +D ?

### ISSUE THREAD

**Issue by natsupy** [wudixiaop/ShaderlabVS#15]
Hi, you can add feature like Ctrl + K + D same NShader, because i add NShader plugin, your extension not work, your extension are awesome !
Thank you so much for that !

**Comment by wudixiaop** [comment]
@natsupy, do you mean the auto format code feature?

**Comment by natsupy** [comment]
no, it's format document, like you use Ctrl K + D on visual studio code, like this:
http://stackoverflow.com/questions/15663447/difference-between-ctrl-k-d-and-ctrl-e-d
or can you help me how can implement both 2 plugin Nshader and your extension, if i implement Nshader( have feature Ctrl + K + D), your plugin not work
NShader(VS 2013 - 2015): http://www.horsedrawngames.com/shader-syntax-highlighting/
Thank you so much !

**Comment by wudixiaop** [comment]
[ShaderlabVS Pro](http://www.amlovey.com/shaderlabvs/#/) has document format feature.
