### ISSUE TITLE
support vs2015

### ISSUE THREAD

**Issue by yanhuifair** [wudixiaop/ShaderlabVS#2]

**Comment by wudixiaop** [comment]
Hi, 

Sorry that I have no resources to work on ShaderlabVS currently, but may be I will improve it when i'm free in future. I recommend Visual Studio Tools for Unity 2.0 plugin to you for now. The plugin have Syntax Hightlighting and outlining too. thank you!

**Comment by wudixiaop** [comment]
Any pull requests are welcome! :smile:

**Comment by wudixiaop** [comment]
Done in v0.6. <https://github.com/wudixiaop/ShaderlabVS/releases/tag/0.6>

**IMPROTANT :** We have to execute vs2015_register.cmd after extension installed to linke .shader and .cginc files to ShaderlabVS content on VS2015. This is not required on VS2013/VS2012.

**Comment by yanhuifair** [comment]
That's great
