### ISSUE TITLE
这个能发布到vs市场上去么？

### ISSUE THREAD

**Issue by OtakuAndFitness** [wudixiaop/ShaderlabVS#29]
就是这个市场https://marketplace.visualstudio.com/
这样方便大家安装

**Comment by wudixiaop** [comment]
有人帮忙发布到 https://marketplace.visualstudio.com/items?itemName=ShaderlabVS2019.ShaderlabVS 了。如果觉得好用，可以支持下 Pro 版本：http://www.amlovey.com/shaderlabvs/#/
