### ISSUE TITLE
unity 2018 后 mvp矩阵有所封装新的api不能提示了

### ISSUE THREAD

**Issue by gaoxiaojiang** [wudixiaop/ShaderlabVS#30]
1、unity 2018 不能用mul去转化MVP会被引擎自动改为UnityObjectToClipPos，但是UnityObjectToClipPos没有智能提示。
2、unity_ObjectToWorld 这些也是2018被修改了。
请问能更新支持2018的这些api吗没有智能提示？谢谢

**Comment by wudixiaop** [comment]
数据已经过时了
