### ISSUE TITLE
Is this project still alive? 

### ISSUE THREAD

**Issue by xCyborg** [wudixiaop/ShaderlabVS#31]
I love this extension but it seems it's not being developed no longer, what's the issue?

**Comment by wudixiaop** [comment]
有人帮忙发布到 https://marketplace.visualstudio.com/items?itemName=ShaderlabVS2019.ShaderlabVS 了。如果觉得好用，可以支持下 Pro 版本：http://www.amlovey.com/shaderlabvs/#/
