### ISSUE TITLE
有人知道Lex数据怎么更新吗

### ISSUE THREAD

**Issue by cloudycliff** [wudixiaop/ShaderlabVS#36]
我做了个fork，可以编译出来2019可用的插件了，但是没搞明白怎么用他的lex工具更新最新的语法文件，有人知道怎么用吗？

**Comment by wudixiaop** [comment]
@cloudycliff gplex 工具的文档可以从这里得到 <https://pan.baidu.com/s/1_f7tVLbMrQi6cVe1nAjMoA>。生成语法文件的代码在这里：<https://github.com/wudixiaop/ShaderlabVS/blob/master/Src/ShaderlabVS.LexTools/Program.cs>

**Comment by cloudycliff** [comment]
@wudixiaop 感谢回复
如果我没理解错的话，lextool会生成shaderlab.lex，然后gplex会解析并生成cs文件。
所以现在的问题是，我要怎么更新Data文件夹下的那些def文件到最新版本的内容？
感谢

**Comment by wudixiaop** [comment]
[ShaderlabVS Pro](http://www.amlovey.com/shaderlabvs/#/) 已经不用 gplex 了，觉得  ShaderlabVS 好用的话，可以支持下 ShaderlabVS Pro 这个长期支持版本。

**Comment by jcs090218** [comment]
我也想知道這個問題, 有任何頭緒嗎?
