### ISSUE TITLE
打开文件之后 我瞬间斯巴达了

### ISSUE THREAD

**Issue by liuyanlin** [wudixiaop/ShaderlabVS#4]
怎么安装？自己生成文件？用vs2015打开文件Shaderlab.cs Shaderlab.lex 丢失 都无法编译

**Comment by wudixiaop** [comment]
Shaderlab.cs Shaderlab.lex 是自动生成的，编译项目就好了。

**Comment by wudixiaop** [comment]
Shaderlab.cs Shaderlab.lex  是自动生成的，编译解决方案就好了
