### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by rrtt2323** [wudixiaop/ShaderlabVS#7]
错误	1	There was a problem validating the xml schema "C:\Users\pc\Desktop\ShaderlabVS-master\Src\ShaderlabVS\obj\Debug\extension.vsixmanifest". 元素 命名空间“http://schemas.microsoft.com/developer/vsx-schema/2011”中的“Metadata”。 的子元素 命名空间“http://schemas.microsoft.com/developer/vsx-schema/2011”中的“DisplayName”。 无效。应为可能元素的列表: 命名空间“http://schemas.microsoft.com/developer/vsx-schema/2011”中的“Identity”。。	ShaderlabVS

**Comment by wudixiaop** [comment]
已经修复了
