### ISSUE TITLE
请求帮助，VS2015企业版无高亮无自动补全

### ISSUE THREAD

**Issue by zwxbest** [wudixiaop/ShaderlabVS#9]
附上安装截图以及日志、
cmd运行结果：
http://7xngf3.com1.z0.glb.clouddn.com/aa.PNG
shader没有高亮
http://7xngf3.com1.z0.glb.clouddn.com/aa2.PNG
已经安装了插件
http://7xngf3.com1.z0.glb.clouddn.com/aa3.PNG
————————————
2016/7/15 12:08:30 - Microsoft VSIX Installer
2016/7/15 12:08:30 - -------------------------------------------
2016/7/15 12:08:30 - Initializing Install...
2016/7/15 12:08:30 - Extension Details...
2016/7/15 12:08:30 - 	Identifier         : ShaderlabVS..c702cfb7-573c-45f4-9469-115fcb519ad2
2016/7/15 12:08:30 - 	Name               : ShaderlabVS
2016/7/15 12:08:30 - 	Author             : Rocky Lai
2016/7/15 12:08:30 - 	Version            : 0.6
2016/7/15 12:08:30 - 	Description        : ShaderlabVS is a Visual Studio plugin for Unity3D shader programming.
2016/7/15 12:08:30 - 	Locale             : zh-CN
2016/7/15 12:08:30 - 	MoreInfoURL        : https://github.com/wudixiaop/ShaderlabVS/blob/master/README.md
2016/7/15 12:08:30 - 	InstalledByMSI     : False
2016/7/15 12:08:30 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2016/7/15 12:08:30 - 
2016/7/15 12:08:30 - 	SignatureState     : Unsigned
2016/7/15 12:08:30 - 	Supported Products : 
2016/7/15 12:08:30 - 		Microsoft.VisualStudio.Pro
2016/7/15 12:08:30 - 			Version : [11.0,12.0]
2016/7/15 12:08:30 - 		Microsoft.VisualStudio.Pro
2016/7/15 12:08:30 - 			Version : [14.0,15.0)
2016/7/15 12:08:30 - 		Microsoft.VisualStudio.VSWinExpress
2016/7/15 12:08:30 - 			Version : [11.0,12.0]
2016/7/15 12:08:30 - 		Microsoft.VisualStudio.VSWinExpress
2016/7/15 12:08:30 - 			Version : [14.0,15.0)
2016/7/15 12:08:30 - 		Microsoft.VisualStudio.Ultimate
2016/7/15 12:08:30 - 			Version : [11.0,12.0]
2016/7/15 12:08:30 - 		Microsoft.VisualStudio.Premium
2016/7/15 12:08:30 - 			Version : [11.0,12.0]
2016/7/15 12:08:30 - 		Microsoft.VisualStudio.VSWinDesktopExpress
2016/7/15 12:08:30 - 			Version : [11.0,12.0]
2016/7/15 12:08:30 - 		Microsoft.VisualStudio.Community
2016/7/15 12:08:30 - 			Version : [14.0,15.0)
2016/7/15 12:08:30 - 		Microsoft.VisualStudio.Enterprise
2016/7/15 12:08:30 - 			Version : [14.0,15.0)
2016/7/15 12:08:30 - 
2016/7/15 12:08:30 - 	References         : 
2016/7/15 12:08:30 - Signature Details...
2016/7/15 12:08:30 - 	Extension is not signed.
2016/7/15 12:08:30 - 
2016/7/15 12:08:30 - Searching for applicable products...
2016/7/15 12:08:30 - Found installed product - Microsoft Visual Studio Enterprise 2015
2016/7/15 12:08:32 - The extension with ID 'ShaderlabVS..c702cfb7-573c-45f4-9469-115fcb519ad2' is not installed to Microsoft Visual Studio Enterprise 2015.
2016/7/15 12:08:32 - Found installed product - Microsoft Visual Studio Professional 2015
2016/7/15 12:08:32 - Found installed product - Microsoft Visual Studio Community 2015
2016/7/15 12:08:32 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
2016/7/15 12:08:32 - Found installed product - Global Location
2016/7/15 12:08:40 - The following target products have been selected...
2016/7/15 12:08:40 - 	Microsoft Visual Studio Enterprise 2015
2016/7/15 12:08:40 - 
2016/7/15 12:08:40 - Beginning to install extension to Microsoft Visual Studio Enterprise 2015...
2016/7/15 12:08:40 - Install to Microsoft Visual Studio Enterprise 2015 completed successfully. The extension has been installed to C:\USERS\ZHANGWEIXIAO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\PTBMHZOF.GJ1\

**Comment by wudixiaop** [comment]
请问下您是安装完插件之后运行的 register.cmd 还是之前运行的呢？

**Comment by wudixiaop** [comment]
需要在安装完插件之后运行cmd。我看您给的图片，像是 register.cmd 没有起作用（它的作用是删除 VS 2015 对 .shader 文件的默认关联）。

**Comment by zwxbest** [comment]
安装完运行的cmd

**Comment by wudixiaop** [comment]
@zwxbest 你好，我修改了下插件。你试试这个版本 http://pan.baidu.com/s/1pLvS52F。 这个插件安装完不需要执行批处理。

建议安装此插件前先把之前安装过的版本卸载掉。

**Comment by wudixiaop** [comment]
Close it. If it's still repro, re-open it later
